name: BitrateViewer

attributes:
  ORGANIZATIONNAME: nuomi1

targets:
  BitrateViewer:
    type: application
    platform: macOS
    deploymentTarget: 11.0
    sources:
      - BitrateViewer
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: ${SRCROOT}/$(PROJECT_NAME)/$(TARGET_NAME).entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.nuomi1.bitrateviewer
        SWIFT_VERSION: 5.0
